// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVqDL246EiAqmvelVm0DysuOfP-a73wK4',
    appId: '1:651429556190:web:dca127e157c70e34c8374f',
    messagingSenderId: '651429556190',
    projectId: 'mindcare-d8c35',
    authDomain: 'mindcare-d8c35.firebaseapp.com',
    storageBucket: 'mindcare-d8c35.appspot.com',
    measurementId: 'G-44JYSMQYNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRZEjrvyqGtVgb8cbkqo1-8Dj1T2j_yk',
    appId: '1:651429556190:android:028899bf520a21b4c8374f',
    messagingSenderId: '651429556190',
    projectId: 'mindcare-d8c35',
    storageBucket: 'mindcare-d8c35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtZ6Z5zsWiKt-77ifRkYibdm_74_yBbQ',
    appId: '1:651429556190:ios:9609193857c3263cc8374f',
    messagingSenderId: '651429556190',
    projectId: 'mindcare-d8c35',
    storageBucket: 'mindcare-d8c35.appspot.com',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtZ6Z5zsWiKt-77ifRkYibdm_74_yBbQ',
    appId: '1:651429556190:ios:51e1495b9fbfee80c8374f',
    messagingSenderId: '651429556190',
    projectId: 'mindcare-d8c35',
    storageBucket: 'mindcare-d8c35.appspot.com',
    iosBundleId: 'com.example.mindcare.RunnerTests',
  );
}
